require 'extension'
require 'initializer'
require 'logging'
require 'output'
require 'setter'
require 'single'

require 'proof/namespace'
require 'proof/description'
require 'proof/extend'
require 'proof/result'
require 'proof/execution'
require 'proof/error'
require 'proof/core_ext'
require 'proof/proof'
require 'proof/output'
require 'proof/suite'
require 'proof/summary'
